### ISSUE TITLE
Match failed [400]

### ISSUE THREAD

**Issue by CoreTea-Solution** [ARKHAM-Enterprises/meteor-comments-ui#41]
Why I'm get this error??? 
```
Exception while simulating the effect of invoking 'comments/add' errorClass {message: "Match error: Expected string, got object", path: "", sanitizedError: errorClass, errorType: "Match.Error"} Error: Match error: Expected string, got object
```
how to i resolve this?

**Comment by matteodem** [comment]
What are you trying to achieve and how can I reproduce this?

**Comment by sladkovm** [comment]
@CoreTea-Solution I sense the question arises from the same newby as me:

In the comments template (in my case it is called "my_template_with_commets") snipped the "id" parameter is important, because it will bind the added comment to the actual, in my case, database item.

Therefore my invoking of the commentBox looks like this:

```
            <div class="comment-section">
                {{> commentsBox id=_id}}
            </div>
```

where _id is a key to the item in my database (document in the collection). Needles to say that the same document in this collection is used to populate the rest of the template. The latter is achieved by passing data through the router:

```
Router.route('/website', function (){ 
   this.render('my_template_with_commets', {
        to:"main",
        data:function(){
            var websiteId = Session.get("website_id"); // I've pre-stored the _id in the Session before
            //console.log(Websites.findOne({_id:website_id}))
            return Websites.findOne({_id:websiteId});
        } 
})
```

**Comment by matteodem** [comment]
Yes exactly, I hope this is resolved. Otherwise feel free to write into this issue.
